//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrixIT.Platform.Modules.Membership.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Interface {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Interface() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StrixIT.Platform.Modules.Membership.Resources.Interface", typeof(Interface).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the terms.
        /// </summary>
        public static string AcceptedTerms {
            get {
                return ResourceManager.GetString("AcceptedTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account overview.
        /// </summary>
        public static string AccountOverviewLink {
            get {
                return ResourceManager.GetString("AccountOverviewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new group.
        /// </summary>
        public static string AddGroup {
            get {
                return ResourceManager.GetString("AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New role.
        /// </summary>
        public static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new user.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string ChangePasswordError {
            get {
                return ResourceManager.GetString("ChangePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must be {0} characters long and contain at least {1} non-alphanumeric characters..
        /// </summary>
        public static string ChangePasswordInstructionsWithNonAlphaNumeric {
            get {
                return ResourceManager.GetString("ChangePasswordInstructionsWithNonAlphaNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must be {0} characters long..
        /// </summary>
        public static string ChangePasswordInstructionsWithoutNonAlphaNumeric {
            get {
                return ResourceManager.GetString("ChangePasswordInstructionsWithoutNonAlphaNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} if you forgot your password.
        /// </summary>
        public static string ChangePasswordLink {
            get {
                return ResourceManager.GetString("ChangePasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new group.
        /// </summary>
        public static string CreateGroup {
            get {
                return ResourceManager.GetString("CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new user account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name and e-mail address for your new account..
        /// </summary>
        public static string CreateNewAccountInstructions {
            get {
                return ResourceManager.GetString("CreateNewAccountInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create role.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new user.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date the user accepted the terms.
        /// </summary>
        public static string DateAcceptedTerms {
            get {
                return ResourceManager.GetString("DateAcceptedTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this e-mail already exists. Please enter a different address..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is in use. Please choose another one..
        /// </summary>
        public static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit group {0}.
        /// </summary>
        public static string EditGroup {
            get {
                return ResourceManager.GetString("EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit role {0}.
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user {0}.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address has been confirmed and your account is now active..
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An e-mail has been send to your e-mail address. Please click the link in the mail to set your password..
        /// </summary>
        public static string EnterPasswordRequested {
            get {
                return ResourceManager.GetString("EnterPasswordRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing your password..
        /// </summary>
        public static string ErrorChangingPassword {
            get {
                return ResourceManager.GetString("ErrorChangingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating your new account.
        /// </summary>
        public static string ErrorCreatingAccount {
            get {
                return ResourceManager.GetString("ErrorCreatingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while registering..
        /// </summary>
        public static string ErrorRegisteringUser {
            get {
                return ResourceManager.GetString("ErrorRegisteringUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending the approved account mail..
        /// </summary>
        public static string ErrorSendingApprovedAccountMail {
            get {
                return ResourceManager.GetString("ErrorSendingApprovedAccountMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed, but an error occurred sending a confirmation mail to your e-mail address. You can ignore this error and login to the site..
        /// </summary>
        public static string ErrorSendingPasswordChangedMail {
            get {
                return ResourceManager.GetString("ErrorSendingPasswordChangedMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending your password reset link..
        /// </summary>
        public static string ErrorSendingPasswordResetLink {
            get {
                return ResourceManager.GetString("ErrorSendingPasswordResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending the unapproved account mail..
        /// </summary>
        public static string ErrorSendingUnapprovedAccountMail {
            get {
                return ResourceManager.GetString("ErrorSendingUnapprovedAccountMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been succesfully created, but an error occurred while sending your account verification mail. Please use the password reset functionality to request a new password and gain access..
        /// </summary>
        public static string ErrorSendingVerificationMail {
            get {
                return ResourceManager.GetString("ErrorSendingVerificationMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while validating your acount..
        /// </summary>
        public static string ErrorValidatingAccount {
            get {
                return ResourceManager.GetString("ErrorValidatingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group index.
        /// </summary>
        public static string GroupIndex {
            get {
                return ResourceManager.GetString("GroupIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups not enabled..
        /// </summary>
        public static string GroupsNotEnabed {
            get {
                return ResourceManager.GetString("GroupsNotEnabed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-mail and/or password is/are incorrect..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password set key is invalid. Please request a new one and try again..
        /// </summary>
        public static string InvalidPasswordSetKey {
            get {
                return ResourceManager.GetString("InvalidPasswordSetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is approved.
        /// </summary>
        public static string IsApprovedTooltip {
            get {
                return ResourceManager.GetString("IsApprovedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user account is locked out.
        /// </summary>
        public static string IsLockedOutTooltip {
            get {
                return ResourceManager.GetString("IsLockedOutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is not yet approved.
        /// </summary>
        public static string IsNotApprovedTooltip {
            get {
                return ResourceManager.GetString("IsNotApprovedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is active.
        /// </summary>
        public static string IsNotLockedOutTooltip {
            get {
                return ResourceManager.GetString("IsNotLockedOutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out.
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked out because of too many invalid login attempts. Please contact your administrator..
        /// </summary>
        public static string LockedOutExplanation {
            get {
                return ResourceManager.GetString("LockedOutExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account locked.
        /// </summary>
        public static string LockedOutStatus {
            get {
                return ResourceManager.GetString("LockedOutStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string LoginFailedContainer {
            get {
                return ResourceManager.GetString("LoginFailedContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail address and password below..
        /// </summary>
        public static string LoginInstructions {
            get {
                return ResourceManager.GetString("LoginInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of users.
        /// </summary>
        public static string MaxNumberOfUsers {
            get {
                return ResourceManager.GetString("MaxNumberOfUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of users for this group has been reached..
        /// </summary>
        public static string MaxNumberOfUsersReached {
            get {
                return ResourceManager.GetString("MaxNumberOfUsersReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No groups available.
        /// </summary>
        public static string NoGroups {
            get {
                return ResourceManager.GetString("NoGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permissions.
        /// </summary>
        public static string NoPermissions {
            get {
                return ResourceManager.GetString("NoPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has no roles.
        /// </summary>
        public static string NoRoles {
            get {
                return ResourceManager.GetString("NoRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password does not match the confirmation.
        /// </summary>
        public static string PasswordAndConfirmationDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordAndConfirmationDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been successfully changed..
        /// </summary>
        public static string PasswordChangeSuccess {
            get {
                return ResourceManager.GetString("PasswordChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An e-mail has been send to the e-mail address you specified. Please click the link in the mail to continue resetting your password..
        /// </summary>
        public static string PasswordResetRequested {
            get {
                return ResourceManager.GetString("PasswordResetRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string PasswordResetRequestedTitle {
            get {
                return ResourceManager.GetString("PasswordResetRequestedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been saved. You can now log in using your new password..
        /// </summary>
        public static string PasswordSetSuccess {
            get {
                return ResourceManager.GetString("PasswordSetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission set.
        /// </summary>
        public static string PermissionSet {
            get {
                return ResourceManager.GetString("PermissionSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions not enabled.
        /// </summary>
        public static string PermissionsNotEnabed {
            get {
                return ResourceManager.GetString("PermissionsNotEnabed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred culture.
        /// </summary>
        public static string PreferredCulture {
            get {
                return ResourceManager.GetString("PreferredCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} if you don&apos;t have an account.
        /// </summary>
        public static string RegisterLink {
            get {
                return ResourceManager.GetString("RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been created successfully. An e-mail has been sent to the e-mail address you entered. It contains a link to verify your account and select a password..
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for registration.
        /// </summary>
        public static string RegistrationComment {
            get {
                return ResourceManager.GetString("RegistrationComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your e-mail address. An e-mail with instructions on how to unlock your account will be sent to you..
        /// </summary>
        public static string RequestNewPasswordInstructions {
            get {
                return ResourceManager.GetString("RequestNewPasswordInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string RequestPasswordResetLink {
            get {
                return ResourceManager.GetString("RequestPasswordResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RoleIndex {
            get {
                return ResourceManager.GetString("RoleIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select password.
        /// </summary>
        public static string SelectPasswordRequestedTitle {
            get {
                return ResourceManager.GetString("SelectPasswordRequestedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request reset link.
        /// </summary>
        public static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop view as.
        /// </summary>
        public static string StopViewAs {
            get {
                return ResourceManager.GetString("StopViewAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you entered is too short. Please enter at least {0} characters..
        /// </summary>
        public static string TooShort {
            get {
                return ResourceManager.GetString("TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has not been approved yet. Please contact your administrator..
        /// </summary>
        public static string Unapproved {
            get {
                return ResourceManager.GetString("Unapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use permissions.
        /// </summary>
        public static string UsePermissions {
            get {
                return ResourceManager.GetString("UsePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no access rights. Please contact your administrator..
        /// </summary>
        public static string UserHasNoRoles {
            get {
                return ResourceManager.GetString("UserHasNoRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User overview.
        /// </summary>
        public static string UserIndex {
            get {
                return ResourceManager.GetString("UserIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0}.
        /// </summary>
        public static string ViewGroup {
            get {
                return ResourceManager.GetString("ViewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current group.
        /// </summary>
        public static string ViewingGroup {
            get {
                return ResourceManager.GetString("ViewingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View role {0}.
        /// </summary>
        public static string ViewRole {
            get {
                return ResourceManager.GetString("ViewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View user {0}.
        /// </summary>
        public static string ViewUser {
            get {
                return ResourceManager.GetString("ViewUser", resourceCulture);
            }
        }
    }
}
