//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Moq;
using StrixIT.Platform.Core;

namespace StrixIT.Platform.Modules.Membership.Tests
{
    public class AccountServiceMock
    {
        #region Private Fields

        private IAccountService _accountService;
        private Mock<IMembershipDataSource> _dataSourceMock = new Mock<IMembershipDataSource>();
        private Mock<IMembershipMailer> _mailerMock = new Mock<IMembershipMailer>();
        private Mock<IRoleManager> _roleManagerMock = new Mock<IRoleManager>();
        private Mock<ISecurityManager> _securityManagerMock = new Mock<ISecurityManager>();
        private Mock<IUserManager> _userManagerMock = new Mock<IUserManager>();
        private Mock<IUserContext> _userMock = new Mock<IUserContext>();

        #endregion Private Fields

        #region Public Constructors

        public AccountServiceMock()
        {
            _userMock.Setup(m => m.Id).Returns(MembershipTestData.AdminId);
            _userMock.Setup(m => m.GroupId).Returns(MembershipTestData.MainGroupId);
            _accountService = new AccountService(_dataSourceMock.Object, _securityManagerMock.Object, _userManagerMock.Object, _roleManagerMock.Object, _mailerMock.Object, _userMock.Object);
        }

        #endregion Public Constructors

        #region Properties

        public IAccountService AccountService
        {
            get
            {
                return _accountService;
            }
        }

        public Mock<IMembershipDataSource> DataSourceMock
        {
            get
            {
                return _dataSourceMock;
            }
        }

        public Mock<IMembershipMailer> MailerMock
        {
            get
            {
                return _mailerMock;
            }
        }

        public Mock<IRoleManager> RoleManagerMock
        {
            get
            {
                return _roleManagerMock;
            }
        }

        public Mock<ISecurityManager> SecurityManagerMock
        {
            get
            {
                return _securityManagerMock;
            }
        }

        public Mock<IUserManager> UserManagerMock
        {
            get
            {
                return _userManagerMock;
            }
        }

        public Mock<IUserContext> UserMock
        {
            get
            {
                return _userMock;
            }
        }

        #endregion Properties
    }
}