//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Moq;
using StrixIT.Platform.Web;
using System;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;

namespace StrixIT.Platform.Modules.Membership.Tests
{
    public sealed class AccountControllerMock : IDisposable
    {
        #region Private Fields

        private Mock<IAccountService> _accountService = new Mock<IAccountService>();
        private Mock<IAuthenticationService> _authService = new Mock<IAuthenticationService>();
        private AccountController _controller;
        private Mock<ControllerContext> _controllerContext = new Mock<ControllerContext>();
        private Mock<HttpContextBase> _httpContext = new Mock<HttpContextBase>();
        private Mock<IIdentity> _identity = new Mock<IIdentity>();
        private Mock<HttpRequestBase> _request = new Mock<HttpRequestBase>();

        #endregion Private Fields

        #region Public Constructors

        public AccountControllerMock()
        {
            _request.Setup(r => r.Url).Returns(new Uri("http://www.strixit.com"));
            _httpContext.Setup(r => r.Request).Returns(_request.Object);
            var principal = new Mock<IPrincipal>();
            principal.Setup(p => p.Identity).Returns(_identity.Object);
            _httpContext.Setup(r => r.User).Returns(principal.Object);
            _controllerContext.Setup(c => c.HttpContext).Returns(_httpContext.Object);
            _controllerContext.Setup(c => c.IsChildAction).Returns(false);
            _controller = new AccountController(_authService.Object, _accountService.Object);
            _controller.ControllerContext = _controllerContext.Object;
        }

        #endregion Public Constructors

        #region Public Properties

        public AccountController AccountController
        {
            get
            {
                return _controller;
            }
        }

        public Mock<IAccountService> AccountServiceMock
        {
            get
            {
                return _accountService;
            }
        }

        public Mock<IAuthenticationService> AuthenticationService
        {
            get
            {
                return _authService;
            }
        }

        public Mock<HttpContextBase> HttpContextBaseMock
        {
            get
            {
                return _httpContext;
            }
        }

        public Mock<IIdentity> IdentityMock
        {
            get
            {
                return _identity;
            }
        }

        public Mock<HttpRequestBase> RequestMock
        {
            get
            {
                return _request;
            }
        }

        #endregion Public Properties

        #region Public Methods

        public void Dispose()
        {
            _controller.Dispose();
        }

        #endregion Public Methods
    }
}