//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Moq;
using StrixIT.Platform.Core;
using StrixIT.Platform.Core.Environment;
using StrixIT.Platform.Web;
using System;
using System.Collections.Generic;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;

namespace StrixIT.Platform.Modules.Membership.Tests
{
    public sealed class AccountControllerMock : IDisposable
    {
        #region Private Fields

        private Mock<IAccountService> _accountService = new Mock<IAccountService>();
        private Mock<IAuthenticationService> _authService = new Mock<IAuthenticationService>();
        private Mock<IConfiguration> _configMock = new Mock<IConfiguration>();
        private AccountController _controller;
        private Mock<ControllerContext> _controllerContext = new Mock<ControllerContext>();
        private Mock<ICultureService> _cultureServiceMock = new Mock<ICultureService>();
        private Mock<IEnvironment> _environmentMock = new Mock<IEnvironment>();
        private Mock<HttpContextBase> _httpContext = new Mock<HttpContextBase>();
        private Mock<IIdentity> _identity = new Mock<IIdentity>();
        private Mock<HttpRequestBase> _request = new Mock<HttpRequestBase>();
        private Mock<IUserContext> _userMock = new Mock<IUserContext>();

        #endregion Private Fields

        #region Public Constructors

        public AccountControllerMock()
        {
            _request.Setup(r => r.Url).Returns(new Uri("http://www.strixit.com"));
            _httpContext.Setup(r => r.Request).Returns(_request.Object);
            _controllerContext.Setup(c => c.HttpContext).Returns(_httpContext.Object);
            _controllerContext.Setup(c => c.IsChildAction).Returns(false);

            var platformConfiguration = new PlatformConfiguration();
            platformConfiguration.ApplicationName = "StrixIT Membership Tests";
            var membershipConfiguration = new MembershipConfiguration();
            membershipConfiguration.UseGroups = true;
            membershipConfiguration.AllowUserRegistration = true;
            membershipConfiguration.AutoApproveUsers = true;
            _configMock.Setup(m => m.GetConfiguration<PlatformConfiguration>()).Returns(platformConfiguration);
            _configMock.Setup(m => m.GetConfiguration<MembershipConfiguration>()).Returns(membershipConfiguration);
            _cultureServiceMock.Setup(c => c.Cultures).Returns(new List<CultureData> { new CultureData { Code = "en", Name = "English" }, new CultureData { Code = "nl", Name = "Nederlands" } });
            _cultureServiceMock.Setup(c => c.DefaultCultureCode).Returns("en");
            _cultureServiceMock.Setup(c => c.CurrentCultureCode).Returns("en");
            _userMock.Setup(m => m.Email).Returns(MembershipTestData.GeneralManager.Email);
            _environmentMock.Setup(e => e.Configuration).Returns(_configMock.Object);
            _environmentMock.Setup(e => e.Cultures).Returns(_cultureServiceMock.Object);
            _environmentMock.Setup(e => e.User).Returns(_userMock.Object);
            _controller = new AccountController(_environmentMock.Object, _authService.Object, _accountService.Object);
            _controller.ControllerContext = _controllerContext.Object;
        }

        #endregion Public Constructors

        #region Public Properties

        public AccountController AccountController
        {
            get
            {
                return _controller;
            }
        }

        public Mock<IAccountService> AccountServiceMock
        {
            get
            {
                return _accountService;
            }
        }

        public Mock<IAuthenticationService> AuthenticationService
        {
            get
            {
                return _authService;
            }
        }

        public Mock<HttpContextBase> HttpContextBaseMock
        {
            get
            {
                return _httpContext;
            }
        }

        public Mock<IIdentity> IdentityMock
        {
            get
            {
                return _identity;
            }
        }

        public Mock<HttpRequestBase> RequestMock
        {
            get
            {
                return _request;
            }
        }

        #endregion Public Properties

        #region Public Methods

        public void Dispose()
        {
            _controller.Dispose();
        }

        #endregion Public Methods
    }
}