//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Moq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using StrixIT.Platform.Core;

namespace StrixIT.Platform.Modules.Membership.Tests
{
    public class DataSourceMock
    {
        private Mock<IMembershipDataSource> _dataSourceMock = new Mock<IMembershipDataSource>();
        private Dictionary<Type, List<object>> _dataLists = new Dictionary<Type, List<object>>();

        public void RegisterData<T>(IEnumerable<T> data) where T : class
        {
            var type = typeof(T);

            if (!_dataLists.ContainsKey(type))
            {
                _dataLists.Add(type, new List<T>().Cast<object>().ToList());
            }

            _dataLists[type] = data.Cast<object>().ToList();
            _dataSourceMock.Setup(s => s.Query<T>()).Returns(_dataLists[type].Cast<T>().AsQueryable());

            if (type.GetProperty("Id") != null)
            {
                _dataSourceMock.Setup(s => s.Find<T>(It.IsAny<object[]>())).Returns<object[]>(p => _dataLists[type].FirstOrDefault(d => (Guid)d.GetPropertyValue("Id") == (Guid)p.First()) as T);
            }
        }

        public Mock<IMembershipDataSource> Mock
        {
            get
            {
                return _dataSourceMock;
            }
        }

        public List<T> DataList<T>()
        {
            var list = _dataLists.ContainsKey(typeof(T)) ? _dataLists[typeof(T)].Cast<T>().ToList() : new List<T>();
            return list;
        }

        public void AddDataItem<T>(T item)
        {
            var type = typeof(T);

            if (!_dataLists.ContainsKey(type))
            {
                throw new KeyNotFoundException();
            }

            _dataLists[type].Add(item);
        }
    }
}
