//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Moq;
using System.Linq;
using System.Collections.Generic;
using System.Security.Principal;
using StrixIT.Platform.Core;

namespace StrixIT.Platform.Modules.Membership.Tests
{
    public class GroupManagerMock
    {
        private IGroupManager _groupManager;
        private DataSourceMock _dataSourceMock = new DataSourceMock();
        private Mock<IGroupManager> _groupManagerMock = new Mock<IGroupManager>();

        public GroupManagerMock()
        {
            _dataSourceMock.RegisterData<Group>(MembershipTestData.Groups);
            _dataSourceMock.RegisterData<User>(MembershipTestData.Users);
            _dataSourceMock.Mock.Setup(d => d.Save<Group>(It.IsAny<Group>())).Returns<Group>(g => g);

            _groupManager = new GroupManager(_dataSourceMock.Mock.Object);
        }

        #region Properties

        public IGroupManager GroupManager
        {
            get
            {
                return _groupManager;
            }
        }

        public Mock<IGroupManager> Mock
        {
            get
            {
                return _groupManagerMock;
            }
        }

        internal DataSourceMock DataSourceMock
        {
            get
            {
                return _dataSourceMock;
            }
        }

        #endregion
    }
}
