//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Moq;
using StrixIT.Platform.Core;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Security.Principal;

namespace StrixIT.Platform.Modules.Membership.Tests
{
    public class RoleManagerMock
    {
        private IRoleManager _roleManager;
        private DataSourceMock _dataSourceMock = new DataSourceMock();
        private Mock<IRoleManager> _managerMock = new Mock<IRoleManager>();

        public RoleManagerMock()
        {
            _dataSourceMock.RegisterData<Application>(new List<Application> { MembershipTestData.Application });
            _dataSourceMock.RegisterData<Role>(MembershipTestData.Roles);
            _dataSourceMock.RegisterData<User>(MembershipTestData.Users);
            _dataSourceMock.RegisterData<Group>(MembershipTestData.Groups);
            _dataSourceMock.RegisterData<GroupInRole>(MembershipTestData.GroupsInRoles);
            _dataSourceMock.RegisterData<UserInRole>(MembershipTestData.UsersInRoles);

            _dataSourceMock.Mock.Setup(m => m.Find<GroupInRole>(It.IsAny<object[]>())).Returns<object[]>(p => _dataSourceMock.DataList<GroupInRole>().FirstOrDefault(r => r.GroupId == (Guid)p[0] && r.RoleId == (Guid)p[1]));
            _dataSourceMock.Mock.Setup(m => m.Find<UserInRole>(It.IsAny<object[]>())).Returns<object[]>(p => _dataSourceMock.DataList<UserInRole>().FirstOrDefault(r => r.GroupRoleGroupId == (Guid)p[0] && r.GroupRoleRoleId == (Guid)p[1] && r.UserId == (Guid)p[2]));

            _roleManager = new RoleManager(_dataSourceMock.Mock.Object);
        }

        #region Properties

        public IRoleManager RoleManager
        {
            get
            {
                return _roleManager;
            }
        }

        public Mock<IRoleManager> Mock
        {
            get
            {
                return _managerMock;
            }
        }

        internal DataSourceMock DataSourceMock
        {
            get
            {
                return _dataSourceMock;
            }
        }

        #endregion

        public void FixRelations()
        {
            foreach (var role in _dataSourceMock.DataList<Role>())
            {
                if (role.Groups == null)
                {
                    role.Groups = new List<GroupInRole>();
                }

                foreach (var group in _dataSourceMock.DataList<Group>())
                {
                    foreach (var groupInRole in group.Roles)
                    {
                        if (groupInRole.RoleId == role.Id)
                        {
                            groupInRole.Role = role;
                            role.Groups.Add(groupInRole);
                        }
                    }
                }
            }
        }
    }
}
