//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Moq;
using StrixIT.Platform.Core;
using System.Collections.Generic;

namespace StrixIT.Platform.Modules.Membership.Tests
{
    public class SecurityManagerMock
    {
        private ISecurityManager _securityManager;
        private DataSourceMock _dataSourceMock = new DataSourceMock();
        private Mock<ISecurityManager> _securityManagerMock = new Mock<ISecurityManager>();

        public SecurityManagerMock()
        {
            _dataSourceMock.RegisterData<UserSecurity>(MembershipTestData.UserSecurity);
            _dataSourceMock.RegisterData<User>(MembershipTestData.Users);
            _dataSourceMock.RegisterData<Role>(MembershipTestData.Roles);
            _securityManager = new SecurityManager(_dataSourceMock.Mock.Object);
        }

        #region Properties

        public ISecurityManager SecurityManager
        {
            get
            {
                return _securityManager;
            }
        }

        public Mock<ISecurityManager> Mock
        {
            get
            {
                return _securityManagerMock;
            }
        }

        internal DataSourceMock DataSourceMock
        {
            get
            {
                return _dataSourceMock;
            }
        }

        #endregion
    }
}
