//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Moq;
using StrixIT.Platform.Core;

namespace StrixIT.Platform.Modules.Membership.Tests
{
    public class SecurityManagerMock
    {
        #region Private Fields

        private Mock<IConfiguration> _configMock = new Mock<IConfiguration>();
        private DataSourceMock _dataSourceMock = new DataSourceMock();
        private ISecurityManager _securityManager;
        private Mock<ISecurityManager> _securityManagerMock = new Mock<ISecurityManager>();

        #endregion Private Fields

        #region Public Constructors

        public SecurityManagerMock()
        {
            _dataSourceMock.RegisterData<UserSecurity>(MembershipTestData.UserSecurity);
            _dataSourceMock.RegisterData<User>(MembershipTestData.Users);
            _dataSourceMock.RegisterData<Role>(MembershipTestData.Roles);

            var platformConfiguration = new PlatformConfiguration();
            platformConfiguration.ApplicationName = "StrixIT Membership Tests";
            var membershipConfiguration = new MembershipConfiguration();
            membershipConfiguration.MinRequiredPasswordLength = 8;
            membershipConfiguration.MinRequiredNonAlphanumericCharacters = 1;
            membershipConfiguration.PasswordHashIterations = 1000;
            membershipConfiguration.MaxInvalidPasswordAttempts = 5;
            membershipConfiguration.PasswordAttemptWindow = 10;
            membershipConfiguration.VerificationIdValidWindow = 120;
            _configMock.Setup(m => m.GetConfiguration<PlatformConfiguration>()).Returns(platformConfiguration);
            _configMock.Setup(m => m.GetConfiguration<MembershipConfiguration>()).Returns(membershipConfiguration);

            _securityManager = new SecurityManager(_dataSourceMock.Mock.Object, _configMock.Object);
        }

        #endregion Public Constructors

        #region Properties

        public Mock<ISecurityManager> Mock
        {
            get
            {
                return _securityManagerMock;
            }
        }

        public ISecurityManager SecurityManager
        {
            get
            {
                return _securityManager;
            }
        }

        internal DataSourceMock DataSourceMock
        {
            get
            {
                return _dataSourceMock;
            }
        }

        #endregion Properties
    }
}