//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Moq;
using System.Linq;

namespace StrixIT.Platform.Modules.Membership.Tests
{
    public class UserManagerMock
    {
        #region Private Fields

        private DataSourceMock _dataSourceMock = new DataSourceMock();
        private Mock<ISecurityManager> _securityManagerMock = new Mock<ISecurityManager>();
        private IUserManager _userManager;
        private Mock<IUserManager> _userManagerMock = new Mock<IUserManager>();

        #endregion Private Fields

        #region Public Constructors

        public UserManagerMock()
        {
            var users = MembershipTestData.Users;
            _dataSourceMock.RegisterData<User>(users);
            _dataSourceMock.RegisterData<UserSecurity>(MembershipTestData.UserSecurity);
            _dataSourceMock.RegisterData<UserSessionStorage>(MembershipTestData.Sessions);
            _dataSourceMock.Mock.Setup(m => m.Query<User>(It.IsAny<string>())).Returns(_dataSourceMock.DataList<User>().AsQueryable());
            _dataSourceMock.Mock.Setup(d => d.Save<User>(It.IsAny<User>())).Returns<User>(u => u);
            _dataSourceMock.Mock.Setup(d => d.Save<UserSecurity>(It.IsAny<UserSecurity>())).Returns<UserSecurity>(s => s);
            _dataSourceMock.Mock.Setup(d => d.Save<UserSessionStorage>(It.IsAny<UserSessionStorage>())).Returns<UserSessionStorage>(s => s);
            _userManager = new UserManager(_dataSourceMock.Mock.Object, _securityManagerMock.Object);
        }

        #endregion Public Constructors

        #region Properties

        public Mock<IUserManager> Mock
        {
            get
            {
                return _userManagerMock;
            }
        }

        public IUserManager UserManager
        {
            get
            {
                return _userManager;
            }
        }

        internal DataSourceMock DataSourceMock
        {
            get
            {
                return _dataSourceMock;
            }
        }

        #endregion Properties
    }
}