//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Moq;
using StrixIT.Platform.Core;
using StrixIT.Platform.Core.Environment;
using System.Linq;

namespace StrixIT.Platform.Modules.Membership.Tests
{
    public class UserManagerMock
    {
        #region Private Fields

        private Mock<IConfiguration> _configMock = new Mock<IConfiguration>();
        private DataSourceMock _dataSourceMock = new DataSourceMock();
        private Mock<ISecurityManager> _securityManagerMock = new Mock<ISecurityManager>();
        private IUserManager _userManager;
        private Mock<IUserManager> _userManagerMock = new Mock<IUserManager>();

        #endregion Private Fields

        #region Public Constructors

        public UserManagerMock()
        {
            var users = MembershipTestData.Users;
            _dataSourceMock.RegisterData<User>(users);
            _dataSourceMock.RegisterData<UserSecurity>(MembershipTestData.UserSecurity);
            _dataSourceMock.Mock.Setup(m => m.Query<User>(It.IsAny<string>())).Returns(_dataSourceMock.DataList<User>().AsQueryable());
            _dataSourceMock.Mock.Setup(d => d.Save<User>(It.IsAny<User>())).Returns<User>(u => u);
            _dataSourceMock.Mock.Setup(d => d.Save<UserSecurity>(It.IsAny<UserSecurity>())).Returns<UserSecurity>(s => s);
            _dataSourceMock.Mock.Setup(d => d.Save<UserSessionStorage>(It.IsAny<UserSessionStorage>())).Returns<UserSessionStorage>(s => s);

            var userMock = new Mock<IUserContext>();
            userMock.Setup(m => m.Id).Returns(MembershipTestData.AdminId);
            userMock.Setup(m => m.GroupId).Returns(MembershipTestData.MainGroupId);

            var platformConfiguration = new PlatformConfiguration();
            platformConfiguration.ApplicationName = "StrixIT Membership Tests";
            platformConfiguration.Cultures = "en,nl";
            var membershipConfiguration = new MembershipConfiguration();
            membershipConfiguration.MinRequiredPasswordLength = 8;
            membershipConfiguration.MinRequiredNonAlphanumericCharacters = 1;

            _configMock.Setup(m => m.GetConfiguration<PlatformConfiguration>()).Returns(platformConfiguration);
            _configMock.Setup(m => m.GetConfiguration<MembershipConfiguration>()).Returns(membershipConfiguration);

            var cultureServiceMock = new Mock<ICultureService>();
            cultureServiceMock.Setup(c => c.CurrentCultureCode).Returns("en");

            var environmentMock = new Mock<IEnvironment>();
            environmentMock.Setup(e => e.Configuration).Returns(_configMock.Object);
            environmentMock.Setup(e => e.User).Returns(userMock.Object);
            environmentMock.Setup(e => e.Cultures).Returns(cultureServiceMock.Object);

            _userManager = new UserManager(_dataSourceMock.Mock.Object, _securityManagerMock.Object, environmentMock.Object);
        }

        #endregion Public Constructors

        #region Properties

        public Mock<IUserManager> Mock
        {
            get
            {
                return _userManagerMock;
            }
        }

        public IUserManager UserManager
        {
            get
            {
                return _userManager;
            }
        }

        internal DataSourceMock DataSourceMock
        {
            get
            {
                return _dataSourceMock;
            }
        }

        #endregion Properties
    }
}