//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using StrixIT.Platform.Core;

namespace StrixIT.Platform.Modules.Membership.Tests
{
    [TestClass]
    public class RoleServiceTests
    {
        private Mock<IUserContext> _userContextMock;

        [ClassInitialize]
        public static void Init(TestContext context)
        {
            DataMapper.CreateMap<Permission, AssignPermissionModel>();
        }

        [TestInitialize]
        public void Init()
        {
            _userContextMock = TestHelpers.MockUserContext();
        }

        [TestMethod()]
        public void GetNewShouldRetrieveFilledRoleModel()
        {
            var mock = new RoleServiceMock();
            mock.RoleManagerMock.Setup(m => m.PermissionQuery()).Returns(MembershipTestData.Permissions.Where(p => p.ApplicationId == MembershipTestData.AppId).AsQueryable());
            var result = mock.RoleService.Get(Guid.Empty);
            Assert.IsNotNull(result);
            Assert.AreEqual(0, result.Permissions.First().Index);
            Assert.AreEqual(3, result.Permissions.Last().Index);
        }

        [TestMethod()]
        public void GetShouldRetrieveFilledRoleModel()
        {
            var mock = new RoleServiceMock();
            mock.RoleManagerMock.Setup(m => m.PermissionQuery()).Returns(MembershipTestData.Permissions.Where(p => p.ApplicationId == MembershipTestData.AppId).AsQueryable());
            mock.RoleManagerMock.Setup(m => m.Get(MembershipTestData.GroupAdminRoleId)).Returns(MembershipTestData.GroupAdminRole);
            mock.RoleManagerMock.Setup(m => m.Query()).Returns(MembershipTestData.Roles.AsQueryable());
            var result = mock.RoleService.Get(MembershipTestData.GroupAdminRoleId);
            Assert.IsNotNull(result);
            Assert.AreEqual(0, result.Permissions.First().Index);
            Assert.AreEqual(3, result.Permissions.Last().Index);
            Assert.AreEqual(true, result.Permissions.ElementAt(1).Selected);
        }
    }
}
