//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Moq;
using StrixIT.Platform.Core;

namespace StrixIT.Platform.Modules.Membership.Tests
{
    public static class TestHelpers
    {
        #region Public Methods

        public static Mock<IUserContext> MockUserContext()
        {
            StrixPlatform.ApplicationId = MembershipTestData.AppId;
            var context = new Mock<IUserContext>();
            context.Setup(m => m.Id).Returns(MembershipTestData.AdminId);
            context.Setup(m => m.GroupId).Returns(MembershipTestData.MainGroupId);
            StrixPlatform.User = context.Object;
            return context;
        }

        #endregion Public Methods
    }
}