//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using Moq;
using StrixIT.Platform.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using StrixIT.Platform.Modules.Membership.Tests;
using System.Reflection;
using System.IO;

namespace StrixIT.Platform.Modules.Membership.Tests
{
    public static class TestHelpers
    {
        public static Mock<IUserContext> MockUserContext()
        {
            StrixPlatform.ApplicationId = MembershipTestData.AppId;
            var context = new Mock<IUserContext>();
            context.Setup(m => m.Id).Returns(MembershipTestData.AdminId);
            context.Setup(m => m.GroupId).Returns(MembershipTestData.MainGroupId);
            StrixPlatform.User = context.Object;
            return context;
        }
    }
}
